name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser chrome

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
